### ISSUE TITLE
A simplified version that can be directly deployed to Vercel

### ISSUE THREAD

**Issue by ourongxing** [wibus-wee/raycast-unblock#60]
### Clear and concise description of the problem

Thank you for your efforts, but I have found that there are some issues with local deployment.  

So I write a simplified version that can be directly deployed to Vercel, no web search, no sync, only openai.

### Suggested solution

[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Fourongxing%2Ffake-raycast-backend&env=APIKey&envDescription=OpenAI%20API%20Key)
[ourongxing/fake-raycast-backend](https://github.com/ourongxing/fake-raycast-backend/tree/main)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by wibus-wee** [comment]
Thank you for your improvement project.

But maybe I won't put it into this project for publicity, because:

1. I don't think this kind of service should run online and be open to the Internet, which is likely to lead to blocking and other situations. You can see my documents, and the deployment methods I wrote are based on local deployment.

2. Excluding my personal reasons, it will make it difficult to write a clear document so that people can understand the connection and differences between the two projects. Of course, if you have any ideas, you are welcome to discuss with me!

Thank you very much for your contribution!

**Comment by ourongxing** [comment]
I use Surge to proxy my network and rewrite the header at the same time. It will cause an infinite loop, but openai needs to be proxied. There is no better deployment method than Vercel.

**Comment by wibus-wee** [comment]
You can use script to achieve it.

It is mentioned in the document that a custom header will be added when the raycast unblock request is requested, and you can deal with whether to process it by judging the header.

Activation-script has also provided similar capabilities.

**Comment by wibus-wee** [comment]
hi. I added your project to the README! Thanks for your contribution!
